#!/bin/bash

echo "🎉 RATHNA Products Deployment Summary"
echo "====================================="
echo ""
echo "✅ Frontend: Built and deployed successfully"
echo "✅ Backend: Built and deployed successfully"
echo "✅ Database: MySQL configured and running"
echo "✅ Web Server: Nginx configured and running"
echo "✅ Services: All systemd services enabled and running"
echo ""
echo "📍 Deployment Details:"
echo "   • Frontend: /var/www/rathnaproducts/frontend/"
echo "   • Backend: /var/www/rathnaproducts/backend/"
echo "   • Uploads: /var/www/rathnaproducts/uploads/"
echo "   • Logs: /var/log/rathnaproducts/"
echo ""
echo "🌐 Access URLs:"
echo "   • Website: http://localhost (redirects to HTTPS)"
echo "   • API: http://localhost/api/"
echo "   • Production: https://rathnaproducts.store (when DNS configured)"
echo ""
echo "🔧 Service Management:"
echo "   • Backend: sudo systemctl {start|stop|restart|status} rathna-backend"
echo "   • Nginx: sudo systemctl {start|stop|restart|status} nginx"
echo "   • MySQL: sudo systemctl {start|stop|restart|status} mysql"
echo ""
echo "📊 Service Status:"
sudo systemctl is-active rathna-backend >/dev/null && echo "   ✅ Backend: Running" || echo "   ❌ Backend: Stopped"
sudo systemctl is-active nginx >/dev/null && echo "   ✅ Nginx: Running" || echo "   ❌ Nginx: Stopped"
sudo systemctl is-active mysql >/dev/null && echo "   ✅ MySQL: Running" || echo "   ❌ MySQL: Stopped"
echo ""
echo "📝 View Logs:"
echo "   • Backend: sudo journalctl -u rathna-backend -f"
echo "   • Nginx: sudo tail -f /var/log/nginx/access.log"
echo "   • MySQL: sudo tail -f /var/log/mysql/error.log"
echo ""
echo "🚀 Your RATHNA Products e-commerce platform is now live!"